version: '3.8'
services:
  fib_db:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=mypasswd
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - frontend

  cache:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend

  fib_calc:
    image: ngsantos/fibcalculator
    restart: always
    depends_on:
      - fib_db
    networks:
      - frontend
      - backend
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB=fib: fib_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypasswd
      REDIS_HOST: cache

networks:
  frontend:
  backend:

volumes:
  db:
    driver: local