version: '3.8'
services:
  fib_db:
    image: postgres:14.3
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=mypasswd
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - frontend

  cache:
    image: redis:7
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend

  fib_calc:
    image: ngsantos/fibcalculator
    container_name: fib_calculator
    restart: always
    depends_on:
      - fib_db
    networks:
      - frontend
      - backend
    
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db:
    driver: local