version: '3.8'
services:
  database:
    image: ngsantos/mypostgres
    container_name: database
    restart: always
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

    networks:
      - frontend
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5


  cache:
    image: redis:7
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  fibonacci:
    image: ngsantos/fibpyweb
    container_name: fib_web
    restart: always
    ports:
      - '5000:5000'
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      - cache
      - database
    networks:
      - frontend
      - backend
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc: 65536
    healthcheck:
      test: ["CMD", "curl", "-F", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: ngsantos/mynginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    depends_on:
      - fibonacci
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
    
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db:
    driver: local