version: '3.8'
services:
  database:
    image: ngsantos/mypostgres
    container_name: database
    restart: always
    environment:
      - POSTGERS_USER=postgres
      - POSTGRES_PASSWORD=mypasswd
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - frontend

  cache:
    image: redis:7
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend

  fibonacci:
    image: ngsantos/fibpyweb
    container_name: fib_web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      - cache
      - database
    networks:
      - frontend
      - backend
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc: 65536
    
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db:
    driver: local