version: '3.8'
services:
  database:
    image: ngsantos/mypostgres
    container_name: database
    restart: always
    environment:
      - POSTGRES_PASSWORD=mypasswd
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - frontend

  cache:
    image: redis:7
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend

  calc:
    image: ngsantos/fibcalculator
    container_name: fib_calculator
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - database
      - cache
    networks:
      - frontend
      - backend
    command: sh -c "python app.py"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db:
    driver: local